name: Check Formatting (comment /format to auto-fix)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format-setup
      - run: ./extras/formatting.sh --check-only
